### ISSUE TITLE
Create cluster with kubernetes/k3s version 1.17.2+k3s1 produces civo CLi error

### ISSUE THREAD

**Issue by mciverza** [civo/kube100#17]
Kube version 1.17.2+k3s1 produces civo CLi error: 
```
 /usr/lib/ruby/2.5.0/rubygems/version.rb:208:in initialize': Malformed version number string 1.17.2+k3s1 (ArgumentError)
```

after using this to create the cluster:
```
civo k3s create test37 --size=g2.xsmall --nodes=1 --version=1.17.2+k3s1 --no-wait --no-switch
```

then trying to list clusters errors out:
```
civo k3s list
```
produces
```
Traceback (most recent call last):
	19: from /usr/local/bin/civo:23:in `<main>'
	18: from /usr/local/bin/civo:23:in `load'
	17: from /var/lib/gems/2.5.0/gems/civo_cli-0.5.8/exe/civo:6:in `<top (required)>'
	16: from /var/lib/gems/2.5.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	15: from /var/lib/gems/2.5.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	14: from /var/lib/gems/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	13: from /var/lib/gems/2.5.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	12: from /var/lib/gems/2.5.0/gems/thor-1.0.1/lib/thor.rb:243:in `block in subcommand'
	11: from /var/lib/gems/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
	10: from /var/lib/gems/2.5.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	 9: from /var/lib/gems/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	 8: from /var/lib/gems/2.5.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	 7: from /var/lib/gems/2.5.0/gems/civo_cli-0.5.8/lib/kubernetes.rb:17:in `list'
	 6: from /var/lib/gems/2.5.0/gems/flexirest-1.9.12/lib/flexirest/result_iterator.rb:43:in `each'
	 5: from /var/lib/gems/2.5.0/gems/flexirest-1.9.12/lib/flexirest/result_iterator.rb:43:in `each'
	 4: from /var/lib/gems/2.5.0/gems/flexirest-1.9.12/lib/flexirest/result_iterator.rb:44:in `block in each'
	 3: from /var/lib/gems/2.5.0/gems/civo_cli-0.5.8/lib/kubernetes.rb:22:in `block in list'
	 2: from /usr/lib/ruby/2.5.0/rubygems/version.rb:199:in `new'
	 1: from /usr/lib/ruby/2.5.0/rubygems/version.rb:199:in `new'
/usr/lib/ruby/2.5.0/rubygems/version.rb:208:in `initialize': Malformed version number string 1.17.2+k3s1 (ArgumentError)
```

this is apparently due to Rancher's use of `+` in their versioning.  as noted by Andy Jeffries on slack.

**Comment by andyjeffries** [comment]
For voting @kaihoffman this could be "Support newer versions of k3s than 1.0.0"

**Comment by avi-av** [comment]
@mciverza 

```
civo k3s create test37 --size=g2.xsmall --nodes=1 --version='1.17.2+k3s1' --no-wait --no-switch
```
works for me.

**Comment by andyjeffries** [comment]
This is now done, we've upgraded to 1.18.6 for all new clusters and the CLI should support it (the new Go-based CLI, not the old unsupported one that @mciverza was using at the time of this issue).
